### ISSUE TITLE
How to test it?

### ISSUE THREAD

**Issue by yellowmamba** [tractorcow/silverstripe-akismet#1]
Hi,

I am wondering is there going to be a new field added to the form that I can see in the source code? I previously installed spamprotector and set up `SpamProtectorManager::update_form` according to their docs [here](https://github.com/silverstripe/silverstripe-spamprotection/blob/master/docs/Install.md), but the problem is with that `update_form` method, I don't receive any emails at all, if I remove it, I can receive emails as normal. So I am not sure whether that has anything to do with properly setting up Akismet.

**Comment by tractorcow** [comment]
Hi @yellowmamba sorry, I should provide a testing process for users of this module, but I'll need to invest some time for this.

In the mean time, do you want to check out the built-in test cases for the required third party module (see https://github.com/tijsverkoyen/Akismet/blob/master/tests/AkismetTest.php) then maybe that will suffice for your debugging needs?

Want to share your form generation code? Did you make sure to set the field mapping in your update_form?

**Comment by yellowmamba** [comment]
I added `$protector = SpamProtectorManager::update_form($form, 'Submit');` after the `$form` generation, but I didn't see any new field (even hidden) before submit field, and it seems to block emails. Now the email works after I remove that line, but I am not sure if Akismet works.

I don't think I will be able to test it using that test suite, as I couldn't find `config.php` there, and no `../../../autoload,php` as well.

**Comment by yellowmamba** [comment]
Hey @tractorcow 

I ran the test cases in that wrapper (BTW, there's been an error in there about namespace that I will make a pull request to fix), all tests come through. But, I am yet to confirm it will work for Silverstripe.

**Comment by tractorcow** [comment]
@yellowmamba it looks like the spamprotector module has just had a major update; I'll include a refresh of this module to cover the new API, and will look at ways of improving the testability of this module.

**Comment by tractorcow** [comment]
I've added a testing documentation section at https://github.com/tractorcow/silverstripe-akismet#testing

This module has been updated to work with the latest spamprotection API. Make sure to upgrade or use version 3.0 if you want to use the old version. Testing docs are added to the new version, but they apply the same to the old version.
