### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by asecondwill** [tractorcow/silverstripe-akismet#2]
The extension is spelled incorrectly in the readme. It should be:

`Config::inst()->update('FormSpamProtectionExtension', 'default_spam_protector', 'AkismetSpamProtector');`

Would it also be possible to get instructions on how to use the akismet wrapper if not using  composer.

Thanks

W

**Comment by tractorcow** [comment]
Ew, spelling mistakes. I'll take care of that!

**Comment by tractorcow** [comment]
Fixed the spelling mistake. I need to make those other docs though.

**Comment by tractorcow** [comment]
Updated https://github.com/tractorcow/silverstripe-akismet/commit/67ae10b24fe631b58008d59bf620f5b907d000b4
